### ISSUE TITLE
Right click on any file -> most options disabled

### ISSUE THREAD

**Issue by keven425** [SublimeText/AdvancedNewFile#140] opened 2015-10-07 21:18 UTC
AdvancedNewFile seems to disable most of my context-menu options on a file:

![screen shot 2015-10-07 at 2 19 15 pm](https://cloud.githubusercontent.com/assets/1742456/10351440/6a89ce9a-6cfe-11e5-9e0a-71297ed523fa.png)

**Comment by FichteFoll** [comment] 2022-07-19 19:01
This is *very* unlikely to be caused by ANF. The only thing I could imagine would be crashing the Python host, but that would only gray out commands that are provided by a plugin (which you may have a couple of because I don't recognize many of them). Either way, a console log would help with debugging this further, but considering the issue is 7 years old I'd rather just close it.

**Closed by FichteFoll** 2022-07-19 19:01 UTC
